# .readthedocs.yaml
# Fichier de configuration Read the Docs
# Voir https://docs.readthedocs.io/en/stable/config-file/v2.html pour plus de détails

# Requis
version: 2

# Spécifiez le système d'exploitation pour la construction
build:
  os: ubuntu-20.04  # Ou "ubuntu-22.04" selon vos besoins
  tools:
    - sphinx

# Construction de la documentation dans le répertoire docs/ avec Sphinx
sphinx:
   configuration: docs/conf.py

# Optionnellement, spécifiez la version de Python et les exigences nécessaires pour construire vos documents
python:
   version: 3.7

formats:
  - epub
  - pdf

# Spécifiez explicitement la version de Python et ses exigences
python:
  install:
    - requirements: docs/requirements.txt 
