[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Chemical Price Research"
authors = [{name = "Saliou", email = "baptiste.saliou@etu.unistra.fr"}]
dynamic = ["version", "description"]